### PR TITLE
fix: index tx keys

### LINKED ISSUE #91: Index should keep track of individual transaction keys
### Problem
In the current system, every time a node receives or creates a new transaction a new ref is added to the index:
https://github.com/myelnet/pop/blob/8796fb3545359bfb3fdcc23ca7c710144afad71c/exchange/index.go#L72-L80
And uses this method to set it in the index:
https://github.com/myelnet/pop/blob/8796fb3545359bfb3fdcc23ca7c710144afad71c/exchange/index.go#L272-L290
This only registers the root of the transaction (PayloadCID). In some situation, the node may retrieve only a single key from the transaction though will set the root in the index, this results in the node thinking it has the full transactions and not querying the network.
### Solution
We need to add a `Keys` field to the `DataRef` struct. The field could be an array or a map. I think a map might be more convenient/faster to check if a key is in the index. So maybe `map[string]bool`. This requires regenerating the cbor file by running (in /exchange) once the new field is added to the struct:
```sh
go generate ./index.go
```
Thinking we could add a convenience method to the `*DataRef`:
```go
if ref.Has("hello.txt") {
```
Then this is mainly used here:
https://github.com/myelnet/pop/blob/8796fb3545359bfb3fdcc23ca7c710144afad71c/exchange/tx.go#L420-L430
Which could become:
```go
func (tx *Tx) IsLocal(key string) bool {
	// We have entries this means the content from this root is stored locally
	if len(tx.entries) > 0 {
		return true
	}
	if ref, err := tx.index.GetRef(tx.root); err != nil {
		return ref.Has(key)
	}
	return true
}
```
Lastly there are a few places it should be updated mainly:
https://github.com/myelnet/pop/blob/8796fb3545359bfb3fdcc23ca7c710144afad71c/exchange/tx.go#L377-L381
which should use keys from all the entries set in the Put step.
https://github.com/myelnet/pop/blob/8796fb3545359bfb3fdcc23ca7c710144afad71c/node/popn.go#L755-L760
I might be forgetting some tests as well.
### Test
If all this goes well, uncommenting this test should pass:
https://github.com/myelnet/pop/blob/8796fb3545359bfb3fdcc23ca7c710144afad71c/node/node_test.go#L532-L549

### PR DESCRIPTION
**Pull request by gallexis**
closes #91

### CODE REVIEW

File: exchange/replication.go [hunk 1]
```diff
@@ -139,9 +139,12 @@ func NewReplication(h host.Host, idx *Index, dt datatransfer.Manager, rtv Routed
...
 	r.dt.SubscribeToEvents(func(event datatransfer.Event, channelState datatransfer.ChannelState) {
-		if event.Code == datatransfer.Error && channelState.Recipient() == h.ID() {
-			// If transfers fail and we're the recipient we need to remove it from our index
-			r.idx.DropRef(channelState.BaseCID())
+		switch event.Code {
+		case datatransfer.Error:
+			if channelState.Recipient() == h.ID() {
+				// If transfers fail and we're the recipient we need to remove it from our index
+				r.idx.DropRef(channelState.BaseCID())
+			}
```
Comment (tchardin) [inline exchange/replication.go:147]:
```suggestion
			}
			case datatransfer.Complete:
			              // Probably can wrap the whole switch in this
			              if channelState.Recipient() == h.ID() {
			                              ref, err := idx.GetRef(channelState.BaseCID())
			                              store, err := idx.GetStore(ref.PayloadCID)
			                              keys, err := utils.IPLDMapKeys(context.TODO(), ref.PayloadCID, store.Loader)
			                              ref.Keys = keys // turn these into bytes
			                              idx.SetRef(ref)
			              }
```

Then in /internal/utils/state.go:
```

func MapKeys(ctx context.Context, root cid.Cid, loader ipld.Loader) ([]string, error) {
	// Turn the CID into an ipld Link interface, this will link to all the children
	lk := cidlink.Link{Cid: root}
	// Create an instance of map builder as we're looking to extract all the keys from an IPLD map
	nb := basicnode.Prototype.Map.NewBuilder()
	// Use a loader from the link to read all the children blocks from a given store
	err := lk.Load(ctx, ipld.LinkContext{}, nb, loader)
	if err != nil {
		return nil, err
	}
	// load the IPLD tree
	nd := nb.Build()
	// Gather the keys in an array
	entries := make([]string, nd.Length())
	it := nd.MapIterator()
	i := 0
	// Iterate over all the map entries
	for !it.Done() {
		k, _, err := it.Next()
		// all succeed or fail
		if err != nil {
			return nil, err
		}
		// The key IPLD node needs to be decoded as a string
		key, err := k.AsString()
		if err != nil {
			return nil, err
		}
		entries[i] = key
		i++
	}
	return entries, nil
}
```

File: exchange/exchange.go [hunk 2]
```diff
@@ -208,11 +208,19 @@ func (e *Exchange) FindAndRetrieve(ctx context.Context, root cid.Cid) error {
...
-		return e.idx.SetRef(&DataRef{
+
+		ref := &DataRef{
 			PayloadCID:  root,
 			StoreID:     tx.StoreID(),
 			PayloadSize: int64(res.Size),
-		})
+			Keys:        [][]byte{},
+		}
+
```
Comment (tchardin) [inline exchange/exchange.go:218]: Reuse MapKeys here:
```suggestion
keys, err := utils.MapKeys(ctx, root, tx.Store().Loader)
```

File: exchange/tx.go [hunk 3]
```diff
@@ -269,26 +269,45 @@ func (tx *Tx) buildRoot() error {
...
-	return &DataRef{
+	ref := &DataRef{
 		PayloadCID:  tx.root,
 		StoreID:     tx.storeID,
 		PayloadSize: tx.size,
 	}
+
+	for key := range tx.entries {
+		ref.Keys = append(ref.Keys, []byte(key))
+	}
```
Comment (tchardin) [inline exchange/tx.go:280]: I think this is find, but we have to make sure this method isn't called when the entries haven't been loaded into memory

File: node/popn.go [hunk 4]
```diff
@@ -760,12 +760,19 @@ func (nd *node) get(ctx context.Context, c cid.Cid, args *GetArgs) error {
 				return err
 			}
 		}
+
 		// Register new blocks in our supply by default
-		err = nd.exch.Index().SetRef(&exchange.DataRef{
+		ref := &exchange.DataRef{
```
Comment (tchardin) [inline node/popn.go:765]: If we're fetching content from an existing ref we should try getting it first:
```suggestion
                 ref, err := nd.exch.Index().GetRef(c)
                 if err != nil {
                 // Create a new ref
		ref = &exchange.DataRef{
		 ...
		 }
		 }
```

File: exchange/replication.go (hunk 1 above)
Comment (tchardin) [reply exchange/replication.go:147]: You can reuse that method in `idx.GetEntries()` checkout the tx.go file

File: exchange/replication.go [hunk 5]
```diff
@@ -347,11 +350,21 @@ func (r *Replication) handleRequest(s network.Stream) {
...
+			Keys:        [][]byte{},
+		}
+
+		r.idx.GetRef(req.PayloadCID)
+
+		//for key := range tx.entries {
+		//	ref.Keys[key] = true
+		//}
+
+		err = r.idx.SetRef(ref)
```
Comment (tchardin) [inline exchange/replication.go:367]: @gallexis l371 is where I was thinking you could iterate directly on channel states based on the channel ID, so you can get the keys and set them on the ref directly. Then you can remove the event subscribe in the NewReplication constructor. Makes sense?

Comment (gallexis) [reply exchange/replication.go:367]: Ah yes indeed it makes more sense like that 👍

File: exchange/tx.go (hunk 3 above)
Comment (tchardin) [reply exchange/tx.go:280]: Yeah you could check the length of `tx.entries` first and if it's empty, run `MapKeys`

File: exchange/replication.go [hunk 6]
```diff
@@ -333,27 +326,63 @@ func (r *Replication) handleRequest(s network.Stream) {
...
 		// Create a new store to receive our new blocks
 		// It will be automatically picked up in the TransportConfigurer
 		storeID := r.idx.ms.Next()
-		err = r.idx.SetRef(&DataRef{
-			PayloadCID:  req.PayloadCID,
-			PayloadSize: int64(req.Size),
-			StoreID:     storeID,
-		})
+
+		ref, err := r.idx.GetRef(req.PayloadCID)
```
Comment (tchardin) [inline exchange/replication.go:341]: You don't need to get the ref here. It shouldn't exist at this point. Maybe you could use that as a way to prevent fetching twice if someone is spamming the network, then you'd need to return if the err isn't nil.

File: exchange/replication.go [hunk 7]
```diff
@@ -333,27 +326,63 @@ func (r *Replication) handleRequest(s network.Stream) {
...
+			switch state.Status() {
+			case datatransfer.Failed, datatransfer.Cancelled:
+				err = r.idx.DropRef(state.BaseCID())
+				if err != nil {
+					log.Error().Err(fmt.Errorf("error when droping ref : %v", err))
+				}
+				return
+
+			case datatransfer.Completed:
+				err = r.idx.SetRef(ref)
```
Comment (tchardin) [inline exchange/replication.go:379]: You need to get the keys here (MapKeys) before setting the ref

File: exchange/tx.go [hunk 8]
```diff
@@ -5,6 +5,7 @@ import (
 	"context"
 	"errors"
 	"fmt"
+	"github.com/myelnet/pop/internal/utils"
```
Comment (tchardin) [inline exchange/tx.go:8]: This can go with the other myel imports below

File: exchange/tx.go [hunk 9]
```diff
@@ -269,26 +270,46 @@ func (tx *Tx) buildRoot() error {
...
 // Ref returns the DataRef associated with this transaction
 func (tx *Tx) Ref() *DataRef {
-	return &DataRef{
+	ref := &DataRef{
 		PayloadCID:  tx.root,
 		StoreID:     tx.storeID,
 		PayloadSize: tx.size,
 	}
+
+	if len(tx.entries) <= 0 {
```
Comment (tchardin) [inline exchange/tx.go:279]: `len` can't be negative

File: exchange/tx.go [hunk 10]
```diff
@@ -269,26 +270,46 @@ func (tx *Tx) buildRoot() error {
...
+		keys, _ := utils.MapKeys(context.TODO(), tx.root, tx.Store().Loader)
+		ref.Keys = keys
+	}
+
+	return ref
```
Comment (tchardin) [inline exchange/tx.go:284]: Same you can create &DataRef below and assign Keys directly

File: internal/utils/stat.go [hunk 11]
```diff
@@ -76,3 +76,37 @@ func Stat(ctx context.Context, store *multistore.Store, root cid.Cid, sel ipld.N
 	})
 	return res, nil
 }
+
+func MapKeys(ctx context.Context, root cid.Cid, loader ipld.Loader) ([][]byte, error) {
```
Comment (tchardin) [inline internal/utils/stat.go:80]: Can you add a comment describing what that function does? Just for future documentation

File: node/popn.go [hunk 12]
```diff
@@ -799,12 +799,22 @@ func (nd *node) get(ctx context.Context, c cid.Cid, args *GetArgs) error {
...
+		if err != nil {
+			ref = &exchange.DataRef{
+				PayloadCID:  c,
+				StoreID:     tx.StoreID(),
+				PayloadSize: int64(res.Size),
+				Keys:        [][]byte{},
+			}
+		}
+
+		if args.Key != "" {
```
Comment (tchardin) [inline node/popn.go:813]: If `args.Key` == ""  we also assume that we just retrieved the whole thing so we're gonna need to get all the entries with MapKeys and set them

File: exchange/replication.go [hunk 13]
```diff
@@ -4,6 +4,7 @@ import (
 	"bufio"
 	"context"
 	"fmt"
+	"github.com/rs/zerolog/log"
```
Comment (tchardin) [inline exchange/replication.go:7]: Are those added up there automatically by intellig?

**Review by tchardin — CHANGES_REQUESTED** [review]
Not sure how I feel about the logging. I've been avoiding any decision on logging strategy so far in the library side (/exchange pkg) so probably use `fmt.Println` and we'll implement a consistent logger across the codebase. Still some missing pieces but you're almost there. Thanks

File: exchange/tx.go (hunk 9 above)
Comment (gallexis) [reply exchange/tx.go:279]: I know but ```len``` returns an int, what if there is a cosmic ray that flips the bit that signs for a + into a - ? 😁

File: exchange/replication.go (hunk 13 above)
Comment (gallexis) [reply exchange/replication.go:7]: Yes but I checked and that was already used somewhere else in the repo so I assumed it was the standard lib we use for logging
